server:
  port: 8091
  servlet: 
    context-path: /sparrow-platform

spring:
  security:
    oauth2:
      resourceserver:        jwt:          jwk-set-uri: http://localhost:6060/.well-known/jwks.json
          issuer-uri: http://localhost:6060
        
      client:
        registration:          sparrow-provider:
            client-id: test-client
            client-authentication-method: header
            client-secret: noonewilleverguess
                    provider:          sparrow-provider: 
            authorization-uri: "https://localhost:6060/oauth/authorize"
            token-uri: "https://localhost:6060/oauth/token"
            user-info-uri: "https://localhost:6060/userinfo"
            user-info-authentication-method: "header"
            jwk-set-uri: "http://localhost:6060/.well-known/jwks.json"
            user-name-attribute: "name"

# security.oauth2.authorizationserver.jwt.enabled: false

#logging:
#  level:
#    root: DEBUG
