swagger: "2.0"
info:
  description: "一个针对企业内部的组织架构、系统权限的管理平台。 业务原理可参考文章 [组织权限管理平台的设计与实现](https://mp.weixin.qq.com/s/h8aS_i3CTvkACsBYgqUipw)。可以使用api key `special-key`来测试本应哟个。"
  version: "1.0.0"
  title: "组织权限管理"
  contact:
    email: "fanmeijian@aliyun.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:6060"
basePath: "/api"
tags:
- name: "组织"
- name: "组织单元"
- name: "岗位"
- name: "职级"
- name: "群组"
- name: "人员"
- name: "菜单"
- name: "功能"
- name: "页面元素"
- name: "文件"
- name: "数据"
- name: "字段"


schemes:
- "https"
- "http"
paths:
  /swdOrganizations:
    post:
      tags:
      - "组织"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SwdOrganization"
      responses:
        "200":
          description: "成功"
          schema:
            $ref: "#/definitions/SwdOrganization"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /swdOrganizations/{id}:
    put:
      tags:
      - "组织"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SwdOrganization"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    get:
      tags:
      - "组织"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SwdOrganization"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - api_key: []
    delete:
      tags:
      - "组织"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /organizationRelation:
    post:
      tags: 
      - "组织"
      summary: "建立组织关系"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SwdOrganizationRelation"
      responses:
        "200":
          description: "添加成功"
          schema:
            $ref: "#/definitions/SwdOrganizationRelation"
    
  /swdUnits:
    post:
      tags:
      - "组织单元"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SwdUnit"
      responses:
        "200":
          description: "添加成功"
          schema:
            $ref: "#/definitions/SwdUnit"
  /swdUnits/{id}:
    put:
      tags:
      - "组织单元"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SwdUnit"
      responses:
        "200":
          description: "成功"
          schema:
            $ref: "#/definitions/SwdUnit"
    get:
      tags:
      - "组织单元"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "成功"
          schema:
            $ref: "#/definitions/SwdUnit"
    delete:
      tags:
      - "组织单元"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "成功"
  /swdRoles:
    post:
      tags:
      - "岗位"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SwdRole"
      responses:
        "200":
          description: "成功"
          schema:
            $ref: "#/definitions/SwdRole"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /swdRoles/{id}:
    put:
      tags:
      - "岗位"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SwdRole"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    get:
      tags:
      - "岗位"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "成功"
          schema:
            $ref: "#/definitions/SwdRole"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - api_key: []
    delete:
      tags:
      - "岗位"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /swdLevels:
    post:
      tags:
      - "职级"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SwdLevel"
      responses:
        "200":
          description: "成功"
          schema:
            $ref: "#/definitions/SwdLevel"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /swdLevels/{id}:
    put:
      tags:
      - "职级"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SwdLevel"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    get:
      tags:
      - "职级"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "成功"
          schema:
            $ref: "#/definitions/SwdLevel"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - api_key: []
    delete:
      tags:
      - "职级"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /swdEmployees:
    post:
      tags:
      - "人员"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SwdEmployee"
      responses:
        "200":
          description: "成功"
          schema:
            $ref: "#/definitions/SwdEmployee"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /swdEmployees/{id}:
    put:
      tags:
      - "人员"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SwdEmployee"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    get:
      tags:
      - "人员"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "成功"
          schema:
            $ref: "#/definitions/SwdEmployee"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - api_key: []
    delete:
      tags:
      - "人员"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  SwdOrganization:
    type: "object"
    properties:
      id:
        type: "string"
      code:
        type: "string"
      name:
        type: "string"
      stat:
        type: "integer"
        format: "int32"
    xml:
      name: "SwdOrganization"
  SwdOrganizationRelation:
    type: "object"
    properties:
      id:
        $ref: "#/definitions/SwdOrganizationRelationPK"
      relation:
        type: "integer"
  SwdOrganizationRelationPK:
    type: "object"
    properties:
      organizationId:
        type: "string"
      tartgetId:
        type: "string"
  SwdUnit:
    type: "object"
    properties:
      id:
        type: "string"
      parentId:
        type: "integer"
      name:
        type: "string"
      stat:
        type: "integer"
        format: "int32"
  SwdRole:
    type: "object"
    properties:
      id:
        type: "string"
      code:
        type: "string"
      name:
        type: "string"
      stat:
        type: "integer"
        format: "int32"
  SwdLevel:
    type: "object"
    properties:
      id:
        type: "string"
      code:
        type: "string"
      name:
        type: "string"
      stat:
        type: "integer"
        format: "int32"
  SwdEmployee:
    type: "object"
    properties:
      username:
        type: "string"
      employeeno:
        type: "string"
      stat:
        type: "string"
      swdUnit:
        $ref: "#/definitions/SwdUnit"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "更多关于本平台详情请参考github wiki"
  url: "https://github.com/fanmeijian/sparrow-platform/wiki"