swagger: "2.0"
info:
  description: "一个针对企业内部的组织架构、系统权限的管理平台。 业务原理可参考文章 [组织权限管理平台的设计与实现](https://mp.weixin.qq.com/s/h8aS_i3CTvkACsBYgqUipw)。可以使用api key `special-key`来测试本应哟个。"
  version: "1.0.0"
  title: "组织权限管理"
  contact:
    email: "fanmeijian@aliyun.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:6060"
basePath: "/api"
tags:
- name: "组织"
  description: "关于组织及组织关系的管理"
- name: "组织单元"
- name: "岗位"
- name: "职级"
- name: "群组"
- name: "人员"
- name: "菜单"
- name: "功能"
- name: "页面元素"
- name: "文件"
- name: "数据"
- name: "字段"


schemes:
- "https"
- "http"
paths:
  /swdOrganizations:
    post:
      tags:
      - "组织"
      summary: "新增一个组织"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/SwdOrganization"
      responses:
        "405":
          description: "Invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /swdOrganizations/{id}:
    put:
      tags:
      - "组织"
      summary: "更新现有组织信息"
      description: ""
      operationId: "updatePet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/SwdOrganization"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    get:
      tags:
      - "组织"
      summary: "根据ID获取组织详情"
      description: "Returns a single pet"
      operationId: "getPetById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/SwdOrganization"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - api_key: []
    delete:
      tags:
      - "组织"
      summary: "删除一个组织"
      description: ""
      operationId: "deletePet"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "id"
        in: "path"
        description: "Pet id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  SwdOrganization:
    type: "object"
    properties:
      id:
        type: "string"
      code:
        type: "string"
      name:
        type: "string"
      stat:
        type: "integer"
        format: "int32"
    xml:
      name: "SwdOrganization"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "更多关于本平台详情请参考github wiki"
  url: "https://github.com/fanmeijian/sparrow-platform/wiki"